name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm install
        working-directory: ./project/Mi-primer-ABMC/backend

      - name: Run backend tests
        run: npm test
        working-directory: ./project/Mi-primer-ABMC/backend
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./project/Mi-primer-ABMC/frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./project/Mi-primer-ABMC/frontend