name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop 

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: npm install
        working-directory: ./project/Mi-primer-ABMC/backend

      - name: Run backend tests
        run: npm test
        working-directory: ./project/Mi-primer-ABMC/backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./project/Mi-primer-ABMC/frontend

      - name: Run frontend tests
        run: npm test
        working-directory: ./project/Mi-primer-ABMC/frontend